### ISSUE TITLE
CourseDisplay továbbfejlesztése

### ISSUE THREAD

**Issue by Horti94** [SzFMV2018-Osz/AutomatedCar-B#40]
**statikus Camera class**

- [x] tartalmazza a megjelenítéshez szükséges változókat, pl TARGET_FPS, WIDTH, HEIGHT, SCALING_FACTOR...

- [x] Stabilizálja az FPS-t, hogy az is az osztályon belül történjen, és ne a Main loopban #42 

Ezen keresztül történik a kirajzolás
- [x] Statikus elemek kirajzolása #16 
- [x] Mozgó elemek kirajzolása #17 

- [x] A kirajzolást úgy valósítja meg, hogy az irányított autó mindig a képernyő közepén legyen

- [x] Az objektumokat a SCALING_FACTOR szerint skálázva jeleníti meg #44

**Comment by pintergreg** [comment]
Ez egyrészt túl absztrakt, kicsit ilyen ernyőtaszk, akár külön is lehetne egy issue a kamera mozgatásnak pl. 
A GH nem kezel issue hierarchiát, de attól kissé fapados módon lehet csinálni. Pl. van egy gyűjtő taszt, aminek minden DoD pontjához van linkelve egy másik issue (annak természetesen vannak DoD pontjai), ha egy „al-issue” kész van, akkor a „gyűjtő issueban is ki lehet egy pontot pipálni.

**Comment by rdani95** [comment]
A Camera class ötletét kukáztuk, redundáns lenne, a renderelést úgyis a CourseDisplaz JPanel-en kell csinalnunk, tehát egybevontuk a kettőt.
